docs(quickstart): add quickstart docs
nymtech/docs pull request #186
Opened 2022-08-23 18:22 UTC by iamonuwa

2022-09-01 10:52 UTC, mfahampshire requested changes
Overall looking good, I've requested some changes. Look forward to seeing the socks5 section once thats done too

2022-09-01 10:52 UTC, mfahampshire commented on docs/quickstart/introduction.md
> +Nym Connect is a one-button interface that is easy to use. With Nym connect, you get 100% privacy on applications you use everyday. Presently, Nym connect has support for telegram, keybase and electr
remove the line "With Nym connect, you get 100% privacy on applications you use everyday." - we dont have SURBs yet and a few other things so this isn't strictly true

2022-09-01 10:52 UTC, mfahampshire commented on docs/quickstart/introduction.md
> +Nym Connect is a one-button interface that is easy to use. With Nym connect, you get 100% privacy on applications you use everyday. Presently, Nym connect has support for telegram, keybase and electr
Change 'Nym connect has support for telegram, keybase and electrum wallets. This means that you can run sock5 proxy on these applications with Nym connect. More services coming soon.' to something like 'Presently Nym Connect allows you to send traffic for supported applications through the mixnet, shielding your metadata from the wider internet. NymConnect currently offers support for Telegram, Keybase, and the Electrum Bitcoin wallet. More services will be added soon."

2022-09-01 10:52 UTC, mfahampshire commented on docs/quickstart/nym-connect.md
> +### Step 1. Download
These steps need a bit of fleshing out - look at the docs for the wallet and copy some of the formatting there :)

2022-09-01 10:52 UTC, mfahampshire commented on docs/quickstart/introduction.md
> +**Nym connect is still in experimental stage. If buggy please send us a [feedback report](https://dyno.gg/form/bbec84eb)**
change 'if buggy' to something more formal e.g. 'if you experience problems or bugs, please send a feedback from'

2022-09-01 10:52 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/nym-connect.md
> +#### Building from source
Just add a note like those at the top of each of the node binary pages that you need to build the monorepo first, and remove this heading

2022-09-01 10:52 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/nym-connect.md
> +Nym connect build for linux currently supports only **debian**. If you wish to run on another distro that is not debian, you'll need to build from source. To build from source, you'll also need a [De
Its not that NymConnect only supports debian, its that the pre-compiled binaries are built for debian-based systems, and if you aren't running on a debian-based flavour of linux you'll need to compile it yourself

2022-09-01 10:52 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/nym-connect.md
> +Nym connect build for linux currently supports only **debian**. If you wish to run on another distro that is not debian, you'll need to build from source. To build from source, you'll also need a [De
You don't need a developer ID - with building the wallet locally you need to comment out some stuff in the config so it doesnt check for a develper token: i imagine we can do something similar here :) 

 see docs/stable/nym-apps/wallet#for-developers

2022-09-01 10:53 UTC, mfahampshire commented
A general comment on this as well - you can remove the numbers from the steps, as we don't do that anywhere else. 

I'd say in general look at the formatting and title-ing of the wallet page and work with that as a template

2022-09-01 10:57 UTC, iamonuwa commented
Thanks. Resolving these comments.

2022-09-05 19:05 UTC, mfahampshire requested changes

2022-09-05 19:05 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/introduction.md
> +Many existing applications are able to use SOCK5 Proxy protocol. With `nym-sock5-client`, applications can bounce their traffic through NYM network. The Nym Sock5 proxy protocol takes a TCP data stre
`NYM` is the token, `Nym` is the network - can you change this please. 

Also typo with `Sock5` needs correcting.

2022-09-05 19:05 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/nym-connect.md
> +On Windows you will see a security warning pop up when you attempt to run Nym connect. We are in the process of getting app store keys from Microsoft so that this doesn't happen. See the section belo
Is this true for NymConnect as well as the wallet?

2022-09-05 19:05 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/nym-connect.md
> +On **all** operating systems:
Have you tested / verified this?

2022-09-05 19:05 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/sock5.md
> +### Download and build Nym binaries
Check the formatting in the other pages and change this please - refer to the 'building nym' page.

2022-09-05 19:05 UTC, mfahampshire commented on versioned_docs/version-stable/quickstart/sock5.md
> +![Nym connect app](/img/docs/keybase-settings.gif)
Why is this here?

2022-09-05 19:06 UTC, iamonuwa commented on versioned_docs/version-stable/quickstart/sock5.md
> +![Nym connect app](/img/docs/keybase-settings.gif)
Removing now

2022-09-05 19:07 UTC, iamonuwa commented on versioned_docs/version-stable/quickstart/nym-connect.md
> +On **all** operating systems:
I'm on mac and tested it on mac. Works

2022-09-05 19:08 UTC, iamonuwa commented on versioned_docs/version-stable/quickstart/nym-connect.md
> +On Windows you will see a security warning pop up when you attempt to run Nym connect. We are in the process of getting app store keys from Microsoft so that this doesn't happen. See the section belo
I get this issue on mac also. Happens to any app download from the internet

2022-09-06 11:48 UTC, mfahampshire commented
Changes LGTM. 

I'm not going to merge this, as I think we can actually use this branch as the jump-off point for a bigger documentation update that the quickstart is the first part of. 

I'm going to move it to draft now and we can keep adding to it.

2022-10-13 13:18 UTC, merged