fix: create and join mixnodes families
nymtech/docs pull request #306
Opened 2023-02-15 21:35 UTC by sven-hash

2023-02-15 21:38 UTC, sven-hash commented
I think it should be better to explain how to use `.env` file instead of copy paste the mnemonic in the terminal since it will stay in bash history

2023-02-17 15:15 UTC, mfahampshire commented
Agree re the `.env`, good idea. 

I have a question re: why you've switched over to use the `nym-cli` instead of `nyxd` - perhaps you could edit the PR and have both options? There will be some people wanting to use `nyxd` imo.

2023-02-17 15:18 UTC, sven-hash commented
Because I didn't find the nyxd binary on the latests release i.e https://github.com/nymtech/nym/releases/tag/nym-binaries-v1.1.9 so I deducted that nym-cli replace nyxd

Let me know what you think

2023-02-17 15:19 UTC, mfahampshire commented
No we don't do a release of the `nyxd` binary, we expect people to compile it themselves right now. `nym-cli` is a nice wrapper tool but not everyone uses it.

2023-02-17 15:34 UTC, sven-hash commented
Added nyxd, but could you please check that the command is correct and maybe add the mixnet contract and validator-variables values

You have the right to edit the file, feel free to adapt

2023-02-23 10:59 UTC, mfahampshire requested changes

2023-02-23 10:59 UTC, mfahampshire commented on src/nodes/mix-node-setup.md
> +             (nym-mixnode - version 1.1.9)
replace version number with variable

2023-02-23 10:59 UTC, mfahampshire commented on src/nodes/mix-node-setup.md
> +             (nym-mixnode - version 1.1.9)
ditto

2023-02-23 10:59 UTC, mfahampshire commented on src/nodes/mix-node-setup.md
> -The `--from` is going to be the mnemonic of the member wanting to join the family:
looks like this line was deleted and not moved anywhere? Its important , so make sure its re-included if its disappeared by accident

2023-02-24 10:12 UTC, merged